name: Service heartbeat monitor

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

permissions:
  contents: write 

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Update heartbeat
        run: |
          echo "- $(date -u '+%Y-%m-%d %H:%M UTC') : service availability check" >> heartbeat.txt

      - name: Commit changes
        run: |
          git config user.name "afganirw07"
          git config user.email "afganirwansyah070708@gmail.com"
          git add heartbeat.txt
          git commit -m "chore: hourly heartbeat" || echo "No changes"

      - name: Push changes
        run: git push
