name: Auto Commit Every Hour

on:
  schedule:
    - cron: "0 * * * *" # tiap jam
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Update heartbeat
        run: |
          echo "Last update: $(date -u)" >> heartbeat.txt

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add heartbeat.txt
          git commit -m "chore: hourly heartbeat" || echo "No changes"

      - name: Push changes
        run: git push
